# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f990c8681e878a1556ad1e0b31d790e6e0b2a227964f89d00b26c9a3065ef2b037d278f97724db90846421fd16b39d4d196bec29939d1337798a810718c3932f

test:
  secret_key_base: fe637f5657807735fe545caae032c9ea6909f5ab9478709c3b33c8b5a8d351ec0c493b01b909c0d502b38b082db163851ca5ed7c02c3446241b6aeaaa7da0ade

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
